# Generated by Django 6.0.4 on 2026-04-26 14:01

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(validators=[users.models.validate_age]),
        ),
    ]
